# Generated by Django 4.0.4 on 2022-06-08 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_alter_teste_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b92e513a-c5b9-4f7a-a555-cf53e52b8dfc'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
