# Generated by Django 4.0.4 on 2022-06-08 12:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_alter_teste_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4a4a293e-07e1-47a6-aee9-16acb98ad94d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
