# Generated by Django 4.0.4 on 2022-06-08 13:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0007_alter_teste_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b2cf02f0-ab6f-454e-af3c-e75ac555e356'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
