# Generated by Django 4.0.4 on 2022-06-08 13:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0008_alter_teste_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5f8898d4-bc93-4bbf-be73-45fc4ac5597b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
