# Generated by Django 4.0.4 on 2022-06-08 12:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TesteUser',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('797c6ee0-c6b0-4f89-ba6f-f8aadffe9000'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TesteEmpresa',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('ce4f79cd-7ebe-46bc-806c-d9ee895e472a'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('rel_users', models.ManyToManyField(related_name='TesteEmpresa', to='m2m.testeuser')),
            ],
        ),
    ]
