# Generated by Django 4.0.4 on 2022-06-08 13:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('m2m', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testeempresa',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4f0bf7b9-4e93-4c98-b414-54109f468f56'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='testeuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0eebfffa-56c2-4803-842b-74d39cd934f7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
