# Generated by Django 4.0.4 on 2022-06-08 13:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('m2m', '0002_alter_testeempresa_id_alter_testeuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testeempresa',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6a849cb5-de54-4e19-8623-94c7d9ec671e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='testeuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
