# Generated by Django 4.0.4 on 2022-06-08 13:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('m2m', '0003_alter_testeempresa_id_alter_testeuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testeempresa',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
