# Generated by Django 4.0.4 on 2022-06-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2m', '0004_alter_testeempresa_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesteProgramador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
